version: '3.9'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: cr_postgres
    environment:
      POSTGRES_DB: community_ride
      POSTGRES_USER: cr_user
      POSTGRES_PASSWORD: cr_dev_pass
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U cr_user -d community_ride']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: cr_redis
    ports:
      - '6379:6379'
    command: redis-server --save "" --appendonly no
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
